create table if not exists public.queue (
  id bigint generated by default as identity primary key,
  appointment_id bigint null references public.appointment(appt_id) on delete set null,
  patient_id bigint not null references public.patient(patient_id),
  dentist_id bigint null references public.dentist(dentist_id),
  room_id bigint null references public.room_info(room_id),
  queue_type text not null check (queue_type in ('APPOINTMENT', 'WALK_IN')),
  status text not null default 'WAITING'
    check (status in ('WAITING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
  check_in_time timestamptz not null default now(),
  started_at timestamptz null,
  completed_at timestamptz null,
  note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.queue
  add column if not exists started_at timestamptz null,
  add column if not exists completed_at timestamptz null;

create unique index if not exists queue_active_appointment_unique
  on public.queue (appointment_id)
  where appointment_id is not null
    and status in ('WAITING', 'ASSIGNED', 'IN_PROGRESS');

create unique index if not exists queue_active_patient_unique
  on public.queue (patient_id)
  where status in ('WAITING', 'ASSIGNED', 'IN_PROGRESS');

create unique index if not exists queue_one_in_progress_per_dentist
  on public.queue (dentist_id)
  where status = 'IN_PROGRESS' and dentist_id is not null;

create index if not exists queue_status_check_in_time_idx
  on public.queue (status, check_in_time);

create index if not exists queue_dentist_status_check_in_time_idx
  on public.queue (dentist_id, status, check_in_time);

create table if not exists public.queue_treatment_record (
  record_id bigint generated by default as identity primary key,
  queue_id bigint not null unique references public.queue(id) on delete cascade,
  patient_id bigint not null references public.patient(patient_id),
  dentist_id bigint not null references public.dentist(dentist_id),
  clinical_examination text null,
  diagnosis text not null,
  treatment_note text not null,
  post_treatment_instructions text null,
  created_at timestamptz not null default now()
);

create table if not exists public.follow_up_notification (
  id bigint generated by default as identity primary key,
  queue_id bigint not null references public.queue(id) on delete cascade,
  patient_id bigint not null references public.patient(patient_id),
  dentist_id bigint not null references public.dentist(dentist_id),
  scheduled_for timestamptz not null,
  reason text not null,
  status text not null default 'PENDING'
    check (status in ('PENDING', 'SENT', 'CANCELLED')),
  created_at timestamptz not null default now()
);

create index if not exists follow_up_notification_due_idx
  on public.follow_up_notification (status, scheduled_for);

create or replace function public.sync_appointment_queue()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_dentist_id bigint;
  v_room_id bigint;
begin
  if new.status = 'Checked-in'
    and old.status is distinct from new.status then
    select s.dentist_id, r.room_id
      into v_dentist_id, v_room_id
    from public.appointment_slot aps
    join public.work_slot ws on ws.slot_id = aps.slot_id
    join public.schedules s on s.schedule_id = ws.schedule_id
    left join public.room_info r on r.dentist_id = s.dentist_id
    where aps.appt_id = new.appt_id
      and aps.is_primary = true
    order by r.room_id
    limit 1;

    insert into public.queue (
      appointment_id,
      patient_id,
      dentist_id,
      room_id,
      queue_type,
      status,
      check_in_time
    )
    values (
      new.appt_id,
      new.patient_id,
      v_dentist_id,
      v_room_id,
      'APPOINTMENT',
      case when v_dentist_id is null then 'WAITING' else 'ASSIGNED' end,
      now()
    )
    on conflict do nothing;
  elsif new.status = 'In-Treatment'
    and old.status is distinct from new.status then
    update public.queue
    set status = 'IN_PROGRESS',
        started_at = coalesce(started_at, now())
    where appointment_id = new.appt_id
      and status in ('WAITING', 'ASSIGNED');
  elsif new.status = 'Completed'
    and old.status is distinct from new.status then
    update public.queue
    set status = 'COMPLETED',
        completed_at = coalesce(completed_at, now())
    where appointment_id = new.appt_id
      and status in ('WAITING', 'ASSIGNED', 'IN_PROGRESS');
  elsif new.status = 'Cancelled'
    and old.status is distinct from new.status then
    update public.queue
    set status = 'CANCELLED',
        completed_at = coalesce(completed_at, now())
    where appointment_id = new.appt_id
      and status in ('WAITING', 'ASSIGNED', 'IN_PROGRESS');
  end if;

  return new;
end;
$$;

drop trigger if exists appointment_sync_queue on public.appointment;

create trigger appointment_sync_queue
after update of status on public.appointment
for each row
execute function public.sync_appointment_queue();

insert into public.queue (
  appointment_id,
  patient_id,
  dentist_id,
  room_id,
  queue_type,
  status,
  check_in_time
)
select
  a.appt_id,
  a.patient_id,
  assignment.dentist_id,
  assignment.room_id,
  'APPOINTMENT',
  case
    when a.status = 'In-Treatment' then 'IN_PROGRESS'
    when assignment.dentist_id is not null then 'ASSIGNED'
    else 'WAITING'
  end,
  coalesce(a.book_time, now())
from public.appointment a
left join lateral (
  select s.dentist_id, r.room_id
  from public.appointment_slot aps
  join public.work_slot ws on ws.slot_id = aps.slot_id
  join public.schedules s on s.schedule_id = ws.schedule_id
  left join public.room_info r on r.dentist_id = s.dentist_id
  where aps.appt_id = a.appt_id
    and aps.is_primary = true
  order by r.room_id
  limit 1
) assignment on true
where a.status in ('Checked-in', 'In-Treatment')
on conflict do nothing;

create or replace function public.set_queue_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists queue_set_updated_at on public.queue;

create trigger queue_set_updated_at
before update on public.queue
for each row
execute function public.set_queue_updated_at();
